### ISSUE TITLE
Blank White Screen

### ISSUE THREAD

**Issue by riley-griffin** [yugako/react-native-searchable-picker#1]
I added in the RNSearchable Component like so (with a normal view and some text surrounding the picker):

<RNSearchablePicker
            onSelect={(item)=>setMethod(item)}
            data={methods2}
            placeholder='Choose an item'
            defaultValue={methods2[0].label}
            containerStyles={{marginHorizontal: 10}}
            listStyles={{maxHeight: 50}}
          />

Where methods2 is:

const methods2 = [{label: 'Blunt', value: 'Blunt'}, {label: 'Bong', value: 'Bong'}];

 and the setMethod comes from the state:

  const [method, setMethod] = useState(defaultMethod);

When I add the picker in, I just get a blank white screen, and when I take it out I have just the normal text there that should be above the picker (behaves normally). Any thoughts why this might occur?

**Comment by olavomello** [comment]
Maybe due Virtualized List Error. I just added a PR to solve this.
